# Generated by Django 4.1.7 on 2023-04-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bautizos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Baut', models.DateTimeField()),
                ('registro_Parroq', models.FileField(null=True, upload_to='archivos/')),
                ('tomo', models.CharField(max_length=50, verbose_name='Tomo')),
                ('pagina', models.IntegerField(verbose_name='Pagina')),
                ('acta', models.IntegerField(verbose_name='Acta')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Canton')),
            ],
        ),
        migrations.CreateModel(
            name='Catequista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Niños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=75)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('fecha_nac', models.DateTimeField()),
                ('colegio', models.CharField(max_length=50)),
                ('año_lectivo', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=75)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('tutor', models.BooleanField(default=False)),
                ('papel_familiar', models.CharField(max_length=1)),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.estadocivil')),
            ],
        ),
        migrations.CreateModel(
            name='Parroquias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Parroquia')),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.canton')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('bautizo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.bautizos')),
                ('niño', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.niños')),
            ],
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.provincias'),
        ),
        migrations.AddField(
            model_name='bautizos',
            name='niño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.niños'),
        ),
        migrations.AddField(
            model_name='bautizos',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.parroquias'),
        ),
        migrations.CreateModel(
            name='Asociacion_Nivel_Catequi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catequista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.catequista')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.inscripcion')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inscripcion.niveles')),
            ],
        ),
    ]
