# Generated by Django 4.1.7 on 2023-04-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='estado_civil',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='EstadoCivil',
        ),
    ]
