# Generated by Django 4.1.7 on 2023-04-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscripcion', '0002_alter_personas_estado_civil_delete_estadocivil'),
    ]

    operations = [
        migrations.AddField(
            model_name='niños',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
