# Generated by Django 4.1.7 on 2023-04-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscripcion', '0003_niños_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='num_hijos',
            field=models.IntegerField(default=0),
        ),
    ]
